// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzL_La7L1ZPMEgnueLNBGGScnPatydRMw',
    appId: '1:329048355964:web:680cad252cd5bbf39185f9',
    messagingSenderId: '329048355964',
    projectId: 'electech-4cf87',
    authDomain: 'electech-4cf87.firebaseapp.com',
    storageBucket: 'electech-4cf87.appspot.com',
    measurementId: 'G-8R5CFBQVV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBudeYk9j5BRayO0_YlWYM-F1luOQ3ijoM',
    appId: '1:329048355964:android:82c78b6b5b16ba469185f9',
    messagingSenderId: '329048355964',
    projectId: 'electech-4cf87',
    storageBucket: 'electech-4cf87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FSjCwJvknS35oK83_b0-13veK_O8Qf8',
    appId: '1:329048355964:ios:daec1e4713c2574e9185f9',
    messagingSenderId: '329048355964',
    projectId: 'electech-4cf87',
    storageBucket: 'electech-4cf87.appspot.com',
    iosBundleId: 'com.example.electech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FSjCwJvknS35oK83_b0-13veK_O8Qf8',
    appId: '1:329048355964:ios:f9027373cea83d619185f9',
    messagingSenderId: '329048355964',
    projectId: 'electech-4cf87',
    storageBucket: 'electech-4cf87.appspot.com',
    iosBundleId: 'com.example.electech.RunnerTests',
  );
}
